SELECT * FROM students ORDER BY AGE ASC;

SELECT * FROM students ORDER BY AGE DESC;

SELECT * FROM students ORDER BY AGE ASC, NAME ASC;

SELECT * FROM students ORDER BY AGE DESC LIMIT 3;

SELECT * FROM students WHERE AGE >= 21 ORDER BY NAME ASC;

SELECT * FROM students ORDER BY ID LIMIT 2 OFFSET 0;

SELECT * FROM students ORDER BY ID LIMIT 2 OFFSET 2;

SELECT NAME, AGE FROM students ORDER BY AGE DESC LIMIT 3;

SELECT * FROM students WHERE AGE > 30;
