DROP table STUDENTS;

CREATE TABLE STUDENTS(
ID numeric primary key,
NAME varchar(50) NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
AGE NUMERIC NOT NULL
);

INSERT INTO STUDENTS(ID,NAME,EMAIL,AGE)
VALUES('01','ABRAR','abrar1hussain23@gmail.com',21),
('01','ABBAS','12356@gmail.com',25);

ALTER TABLE STUDENTS ADD COLUMN PHONE_NO NUMERIC;

ALTER TABLE STUDENTS RENAME COLUMN PHONE_NO TO PH_NUMBER;

ALTER TABLE STUDENTS DROP COLUMN PH_NUMBER;
 